os:
- linux
- osx
# - windows
dist: xenial
language: node_js
node_js: node
cache:
  npm: true
  directories:
  - ~/.cache # Cypress binary
matrix:
  fast_finish: true
addons:
  apt:
    packages:
    - xvfb
    - libgtk2.0-0
    - libnotify-dev
    - libgconf-2.4
    - libnss3
    - libxss1
    - libasound2
install:
- npm ci --prefix api
- npm ci --prefix client
script:
- npm run test:ci --prefix client
- npm run e2e --prefix client
