os:
- linux
- osx
# - windows
dist: xenial
language: node_js
node_js: node
cache:
  npm: true
  directories:
  - ~/.cache # Cypress binary
matrix:
  fast_finish: true
services:
  -mongodb
addons:
  apt: # Linux packages needed for Cypress
    packages:
    - xvfb
    - libgtk2.0-0
    - libnotify-dev
    - libgconf-2.4
    - libnss3
    - libxss1
    - libasound2
install:
- npm ci --prefix api
- npm ci --prefix client
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis", pwd:"test",roles:["readWrite"]});'
script:
- NODE_ENV=test npm run test --prefix api
- npm run test:ci --prefix client
- npm run e2e --prefix client
